name: Java image release github workflow

on:
  workflow_call:
    inputs:
      app-name:
        required: false
        type: string
        default: ${{ github.event.repository.name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifact-${{ inputs.app-name }}-java
