name: Java image release github workflow

on:
  workflow_call:
    inputs:
      app-name:
        required: false
        type: string
        default: ${{ github.event.repository.name }}
      otel-version:
        required: false
        type: string
        default: '2.3.0'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifact-${{ inputs.app-name }}-java
          path: artifacts

      - name: List target directory contents
        run: |
          echo "Working directory: $(pwd)"
          ls -la artifacts/
          ls -la artifacts/*.jar || echo "No JAR files found"

      - name: Download OpenTelemetry Agent
        run: |
            mkdir -p opentelemetry
            wget -O opentelemetry/opentelemetry-javaagent.jar \
              https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v${{ inputs.otel-version }}/opentelemetry-javaagent.jar
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

